require conf/distro/poky.conf

DISTRO = "blackhole"
DISTRO_NAME = "Blackhole OS"
DISTRO_VERSION = "0.1.0"
DISTRO_CODENAME = "event-horizon"

# systemd + Wayland + RAUC + radios
DISTRO_FEATURES:append = " systemd wayland opengl pam rauc wifi bluetooth"
DISTRO_FEATURES:remove = "x11 sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED:append = " sysvinit"
VIRTUAL-RUNTIME_initscripts = ""

# Prefer Wayland Chromium
PREFERRED_PROVIDER_virtual/wpebackend = ""

# Image / update defaults
IMAGE_FSTYPES:append = " ext4 wic wic.bmap"
INIT_MANAGER = "systemd"
